spring:
  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migrations
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  jmx:
    enabled: true
  data:
    rest:
      base-path: /datarest
      detection-strategy: annotated

management:
  endpoints:
    web:
      exposure:
        include: health, logfile, metrics
  endpoint:
    health:
      show-details: always
    logfile:
      access: read_only
  health:
    defaults:
      enabled: true

logging:
  file:
    name: /logs/appLog.log

