spring:
  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migrations
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

