services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "migratedb"
    ports:
      - "5434:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
        volume: {}

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=maindb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  pgdata:
    name: postgres-container_pgdata