spring:
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
  data:
    mongodb:
      host: "localhost"
      port: 27017
      username: "user"
      password: "123"
      database: "maindb"
      auto-index-creation: true
  datasource:
    url: jdbc:postgresql://localhost:5434/migratedb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 12345
    hikari:
      maximum-pool-size: 5
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  flyway:
    locations: classpath:db/migrations
    enabled: true
    user: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mongock:
  runner-type: "InitializingBean"
  enabled: true
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
  change-logs-scan-package: "com.galaxy13.hw.migrations"

