spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

application:
  rightAnswersPercentageToPass: 80
  locale: ru-RU235234
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv