spring:
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migrations
    enabled: true
